// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/contact.tsx";
import * as $3 from "./routes/countdown.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/projects/[slug].tsx";
import * as $$0 from "./islands/Countdown.tsx";
import * as $$1 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/contact.tsx": $2,
    "./routes/countdown.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/projects/[slug].tsx": $5,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
    "./islands/Counter.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
